name: Andy personal box
favicon: null
layout_spectrum: 0
typography_spectrum: 0.87296
title: My personal space
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d0c8b4'
    - '#9ca39b'
    - '#626b5b'
    - '#142b2f'
    - '#010204'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
